### ISSUE TITLE
Allow using is not in the [package.metadata.patch] section of Cargo.toml.

### ISSUE THREAD

**Issue by Swoorup** [mokeyish/cargo-patch-crate#7]
Currently with cargo workspace I get,

```toml
[workspace.metadata.patch]
crates = [
  "serde"
]
```

```shell
⚠ crate: serde is not in the [package.metadata.patch] section of Cargo.toml. Did you forget to add it?
```

Perhaps this tool should relax rules when working with cargo workspaces project?
